# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b828ea589e6d59f7a5400fd50f0a0b4c68afec08f005c4c5eeeedc53b25d2ffb5c2cf1165a04fca695c978999d54bf6cf51169b57230c92aa54f0fcb9a4ccd96

test:
  secret_key_base: d7b233a88c9f8ee61f8f103a87baff8dfa2bb0cf4dc5222072ca5784ab7171a93f19f809b141e955c0540230120cb27e80aa5c26bed91dbca8c77b766dc6052c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
